domain_path: C:\Users\alanf\dev\homelab\projects\desk-cube\board\vitis\zynq_baremetal_platform\export\zynq_baremetal_platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\2025.1.1\Vitis\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
