domain_path: C:\Users\alanf\dev\desk-cube\board\vitis\zynq_platform\export\zynq_platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\2025.1.1\Vitis\data\embeddedsw\lib\sw_apps\empty_application
template: empty_application
lang: c
